(function(){"use strict";const $=s=>document.querySelector(s),fid=new URLSearchParams(location.search).get('id'),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':'&quot;',"'":'&#39;'}[c])),media=u=>window.VinciMedia?.resolveUrl?window.VinciMedia.resolveUrl(u):Promise.resolve(u);if(!fid)return;let user=null,f=null,me=null,other=null;
async function load(){const{data:fr,error}=await db.from('vinci_friendships').select('*').eq('id',fid).maybeSingle();if(error||!fr)return location.replace('friends.html');f=fr;const ids=[fr.user_a,fr.user_b],{data:ps}=await db.from('profiles').select('id,username,name,avatar_url').in('id',ids);me=(ps||[]).find(x=>x.id===user.id)||{};other=(ps||[]).find(x=>x.id!==user.id)||{};renderHeader();await Promise.all([loadStats(),loadRooms(),loadMemories()])}
function pic(slot,p){slot.dataset.userId=p.id||'';slot.innerHTML=`<img src="${esc(p.avatar_url||'assets/default-avatar.png.png')}" onerror="this.src='assets/default-avatar.png.png'">`}
function renderHeader(){pic($('#friendshipMe'),me);pic($('#friendshipOther'),other);$('#friendshipTitle').textContent=`Você + @${other.username||'amigo'}`;const days=Math.max(1,Math.floor((Date.now()-new Date(f.created_at))/86400000));$('#friendshipSince').textContent=`Amigos há ${days} dia${days===1?'':'s'} • desde ${new Date(f.created_at).toLocaleDateString('pt-BR')}`;$('#friendshipMessage').href=`direct-chat.html?id=${fid}`;$('#friendshipCapsule').href=`capsules.html?friendship_id=${fid}`}
async function commonRoomIds(){const{data:mine}=await db.from('vinci_room_members').select('room_id').eq('user_id',user.id),{data:theirs}=await db.from('vinci_room_members').select('room_id').eq('user_id',other.id);const a=new Set((mine||[]).map(x=>x.room_id));return(theirs||[]).map(x=>x.room_id).filter(id=>a.has(id))}
async function loadStats(){const roomIds=await commonRoomIds();const[{count:messages},{data:entries},{data:fp}]=await Promise.all([db.from('vinci_direct_messages').select('*',{count:'exact',head:true}).eq('friendship_id',fid),roomIds.length?db.from('vinci_room_entries').select('challenge_id,user_id,room_id').in('room_id',roomIds).in('user_id',[user.id,other.id]):Promise.resolve({data:[]}),db.from('vinci_friendship_progress').select('*').eq('friendship_id',fid).maybeSingle()]);const challengeMap=new Map();for(const e of entries||[]){if(!challengeMap.has(e.challenge_id))challengeMap.set(e.challenge_id,new Set());challengeMap.get(e.challenge_id).add(e.user_id)}const murals=[...challengeMap.values()].filter(s=>s.size===2).length,days=Math.max(1,Math.floor((Date.now()-new Date(f.created_at))/86400000));const vals=[messages||0,roomIds.length,murals,days,fp?.streak_weeks||0];document.querySelectorAll('#friendshipStats strong').forEach((el,i)=>el.textContent=vals[i]??0)}
async function loadRooms(){const ids=await commonRoomIds();if(!ids.length){$('#friendshipRooms').innerHTML='<div class="friendship-state">Vocês ainda não estão em nenhuma Room juntos.</div>';return}const{data}=await db.from('vinci_rooms').select('id,name,cover_url,accent_color').in('id',ids);let h='';for(const r of data||[]){const cover=r.cover_url?await media(r.cover_url):null;h+=`<a class="friendship-room" href="room.html?id=${r.id}"><div class="cover" style="background:${esc(r.accent_color||'#f4a261')}">${cover?`<img src="${esc(cover)}">`:esc((r.name||'R')[0])}</div><div><strong>${esc(r.name)}</strong><small>Room de vocês</small></div></a>`}$('#friendshipRooms').innerHTML=h}
async function loadMemories(){const ids=await commonRoomIds();if(!ids.length){$('#friendshipMemories').innerHTML='<div class="friendship-state">Os próximos momentos de vocês vão aparecer aqui.</div>';return}const{data}=await db.from('vinci_room_entries').select('image_url,user_id,created_at').in('room_id',ids).in('user_id',[user.id,other.id]).order('created_at',{ascending:false}).limit(18);if(!data?.length){$('#friendshipMemories').innerHTML='<div class="friendship-state">Os próximos momentos de vocês vão aparecer aqui.</div>';return}let h='';for(const e of data){h+=`<div class="friendship-memory"> <img src="${esc(await media(e.image_url)||'')}" alt="Memória"></div>`}$('#friendshipMemories').innerHTML=h}
async function loadFavorite(){const{data}=await db.from('vinci_friend_favorites').select('friendship_id').eq('user_id',user.id).eq('friendship_id',fid).maybeSingle();const b=$('#favoriteFriendButton');b.textContent=data?'★':'☆';b.dataset.active=data?'1':'0'}
async function toggleFavorite(){const b=$('#favoriteFriendButton');if(b.dataset.active==='1'){await db.from('vinci_friend_favorites').delete().eq('user_id',user.id).eq('friendship_id',fid)}else{await db.from('vinci_friend_favorites').insert({user_id:user.id,friendship_id:fid})}await loadFavorite()}
async function unfriend(){if(!confirm('Desfazer esta amizade?'))return;const{error}=await db.rpc('vinci_unfriend',{p_friendship_id:fid});if(error)return alert(error.message);location.replace('friends.html')}
async function block(){if(!confirm(`Bloquear @${other.username||'usuário'}? A amizade será removida.`))return;const{error}=await db.rpc('vinci_block_user',{p_user_id:other.id});if(error)return alert(error.message);location.replace('friends.html')}
async function report(){const reason=prompt('Conte em poucas palavras o motivo da denúncia:');if(!reason)return;const{error}=await db.rpc('vinci_report_user',{p_user_id:other.id,p_reason:reason,p_context_type:'friendship',p_context_id:fid});if(error)return alert(error.message);alert('Denúncia registrada.');$('#friendshipMenu').classList.add('hidden')}
async function init(){const{data:{user:u}}=await db.auth.getUser();if(!u)return;user=u;$('#friendshipBack').onclick=()=>history.length>1?history.back():location.assign('friends.html');$('#friendshipMore').onclick=()=>$('#friendshipMenu').classList.toggle('hidden');$('#favoriteFriendButton').onclick=toggleFavorite;$('#closeFriendshipMenu').onclick=()=>$('#friendshipMenu').classList.add('hidden');$('#unfriendButton').onclick=unfriend;$('#blockFriendButton').onclick=block;$('#reportFriendButton').onclick=report;await load();await loadFavorite()}document.addEventListener('DOMContentLoaded',init)})();
