(function(){"use strict";
async function boot(){const actions=document.querySelector('.profile-actions');if(!actions)return;const{data:{user}}=await db.auth.getUser();if(!user)return;const id=new URLSearchParams(location.search).get('id')||user.id;if(id===user.id)return;
const [{data:fs},{data:reqs}]=await Promise.all([db.from('vinci_friendships').select('*').or(`and(user_a.eq.${user.id},user_b.eq.${id}),and(user_a.eq.${id},user_b.eq.${user.id})`).limit(1),db.from('vinci_friend_requests').select('*').eq('status','pending').or(`and(sender_id.eq.${user.id},recipient_id.eq.${id}),and(sender_id.eq.${id},recipient_id.eq.${user.id})`).limit(1)]);const f=fs?.[0],r=reqs?.[0];const wrap=document.createElement('div');wrap.className='vinci-friend-buttons focus-visitor-actions';
function moreMenu(items){return `<div class="focus-visitor-more"><button type="button" data-visitor-more aria-label="Mais opções">•••</button><div class="focus-visitor-menu hidden">${items}</div></div>`}
if(f){wrap.innerHTML=`<a class="button primary" href="direct-chat.html?id=${encodeURIComponent(f.id)}">Mensagem</a><button class="button secondary" type="button" disabled>✓ Amigos</button>${moreMenu(`<a href="friendship.html?id=${encodeURIComponent(f.id)}">Ver amizade</a><a href="albums.html?id=${encodeURIComponent(id)}">Álbuns</a>`)}`}
else if(r){if(r.recipient_id===user.id)wrap.innerHTML=`<button class="button primary" id="acceptProfileFriend">Aceitar</button>${moreMenu('<button type="button" class="danger" id="declineProfileFriend">Recusar pedido</button>')}`;else wrap.innerHTML=`<button class="button secondary" disabled>Pedido enviado</button>${moreMenu(`<a href="albums.html?id=${encodeURIComponent(id)}">Álbuns</a>`)}`}
else wrap.innerHTML=`<button class="button primary" id="addProfileFriend">Adicionar amigo</button>${moreMenu(`<a href="albums.html?id=${encodeURIComponent(id)}">Álbuns</a>`)}`;
actions.appendChild(wrap);const more=wrap.querySelector('[data-visitor-more]'),menu=wrap.querySelector('.focus-visitor-menu');if(more&&menu){more.onclick=()=>menu.classList.toggle('hidden');document.addEventListener('click',e=>{if(!wrap.contains(e.target))menu.classList.add('hidden')})}
document.getElementById('addProfileFriend')?.addEventListener('click',async()=>{const{data:p}=await db.from('profiles').select('username').eq('id',id).single();const{error}=await db.rpc('vinci_send_friend_request',{p_username:p.username});if(error)return alert(error.message);location.reload()});document.getElementById('acceptProfileFriend')?.addEventListener('click',async()=>{const{error}=await db.rpc('vinci_respond_friend_request',{p_request_id:r.id,p_accept:true});if(error)return alert(error.message);location.reload()});document.getElementById('declineProfileFriend')?.addEventListener('click',async()=>{const{error}=await db.rpc('vinci_respond_friend_request',{p_request_id:r.id,p_accept:false});if(error)return alert(error.message);location.reload()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot()})();