(function(){"use strict";const $=s=>document.querySelector(s),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));let user=null,profiles=new Map();
async function loadProfiles(ids){const list=[...new Set(ids.filter(Boolean))];if(!list.length)return;const{data}=await db.from('profiles').select('id,username,name,avatar_url').in('id',list);for(const p of data||[])profiles.set(p.id,p)}
function avatar(p){return p?.avatar_url||'assets/default-avatar.png.png'}
async function load(){const [{data:f,error:fe},{data:r,error:re}]=await Promise.all([db.from('vinci_friendships').select('*').or(`user_a.eq.${user.id},user_b.eq.${user.id}`).order('created_at',{ascending:false}),db.from('vinci_friend_requests').select('*').eq('recipient_id',user.id).eq('status','pending').order('created_at',{ascending:false})]);if(fe||re){$('#friendsList').innerHTML='<div class="friends-state">Instale o PATCH 10 Social Expansion no Supabase.</div>';return}const friends=f||[],requests=r||[];const ids=[...friends.map(x=>x.user_a===user.id?x.user_b:x.user_a),...requests.map(x=>x.sender_id)];await loadProfiles(ids);renderFriends(friends);renderRequests(requests)}
function renderFriends(rows){$('#friendsCount').textContent=`${rows.length} amizade${rows.length===1?'':'s'}`;if(!rows.length){$('#friendsList').innerHTML='<div class="friends-state"><strong>Ainda não há amizades.</strong><br>Adicione alguém pelo @ para começar.</div>';return}$('#friendsList').innerHTML=rows.map(f=>{const oid=f.user_a===user.id?f.user_b:f.user_a,p=profiles.get(oid)||{};return `<article class="friend-card" data-user-id="${oid}"><img class="friend-avatar" src="${esc(avatar(p))}" onerror="this.src='assets/default-avatar.png.png'"><div class="friend-main"><strong>@${esc(p.username||'usuario')}</strong><small>${esc(p.name||'')} • amigos desde ${new Date(f.created_at).toLocaleDateString('pt-BR')}</small></div><div class="friend-actions"><a class="primary" href="direct-chat.html?id=${encodeURIComponent(f.id)}">Mensagem</a><a href="friendship.html?id=${encodeURIComponent(f.id)}">Amizade</a></div></article>`}).join('')}
function renderRequests(rows){const sec=$('#friendRequestsSection');sec.classList.toggle('hidden',!rows.length);$('#friendRequestsCount').textContent=rows.length?String(rows.length):'';$('#friendRequestsList').innerHTML=rows.map(r=>{const p=profiles.get(r.sender_id)||{};return `<article class="friend-request"><img class="friend-avatar" src="${esc(avatar(p))}" onerror="this.src='assets/default-avatar.png.png'"><div class="friend-main"><strong>@${esc(p.username||'usuario')}</strong><small>quer ser seu amigo</small></div><div class="friend-actions"><button class="accept" data-respond="${r.id}" data-accept="1">Aceitar</button><button class="decline" data-respond="${r.id}" data-accept="0">Recusar</button></div></article>`}).join('');document.querySelectorAll('[data-respond]').forEach(b=>b.onclick=()=>respond(b.dataset.respond,b.dataset.accept==='1'))}
async function respond(id,accept){const{error}=await db.rpc('vinci_respond_friend_request',{p_request_id:id,p_accept:accept});if(error)return alert(error.message);await load()}
async function send(){const input=$('#friendUsername'),msg=$('#friendAddMessage'),value=input.value.trim();if(!value)return;$('#sendFriendRequest').disabled=true;const{error}=await db.rpc('vinci_send_friend_request',{p_username:value});$('#sendFriendRequest').disabled=false;if(error){msg.textContent=error.message;return}msg.textContent='Pedido enviado 🧡';input.value='';setTimeout(closeModal,800)}
function openModal(){$('#friendAddModal').classList.remove('hidden');$('#friendUsername').focus()}function closeModal(){$('#friendAddModal').classList.add('hidden');$('#friendAddMessage').textContent=''}
async function init(){const{data:{user:u}}=await db.auth.getUser();if(!u)return;user=u;$('#friendsBack').onclick=()=>history.length>1?history.back():location.assign('profile.html');$('#openFriendAdd').onclick=openModal;$('#closeFriendAdd').onclick=closeModal;$('#sendFriendRequest').onclick=send;$('#friendUsername').onkeydown=e=>{if(e.key==='Enter')send()};$('#friendAddModal').onclick=e=>{if(e.target.id==='friendAddModal')closeModal()};await load();db.channel(`friends-${user.id}`).on('postgres_changes',{event:'*',schema:'public',table:'vinci_friend_requests'},load).on('postgres_changes',{event:'*',schema:'public',table:'vinci_friendships'},load).subscribe()}
document.addEventListener('DOMContentLoaded',init)})();
