(function(){"use strict";
function loadImage(file){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{URL.revokeObjectURL(url);resolve(img)};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error("Não foi possível abrir esta imagem."))};img.src=url})}
function canvasBlob(canvas,type="image/webp",quality=.9){return new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error("Não foi possível preparar a imagem.")),type,quality))}
async function open(file,options={}){const image=await loadImage(file),kind=options.kind==="banner"?"banner":"avatar",aspect=Number(options.aspect)||(kind==="banner"?4:1),outputWidth=Number(options.outputWidth)||(kind==="banner"?1600:640),outputHeight=Number(options.outputHeight)||Math.round(outputWidth/aspect);
return new Promise((resolve,reject)=>{const overlay=document.createElement("div");overlay.className="vinci-cropper";overlay.innerHTML=`<section class="vinci-cropper-card" role="dialog" aria-modal="true"><header class="vinci-cropper-head"><div><span>Vinci 1.1 Focus</span><h2>${options.title||(kind==="banner"?"Enquadrar banner":"Enquadrar foto")}</h2></div><button type="button" class="vinci-cropper-close" aria-label="Cancelar">×</button></header><div class="vinci-cropper-body"><div class="vinci-cropper-stage ${kind}"><canvas></canvas><div class="vinci-cropper-mask"></div></div><p class="vinci-cropper-help">Arraste a foto para posicionar. Use o controle para aproximar ou afastar.</p><label class="vinci-cropper-control"><span>−</span><input type="range" min="1" max="3" step="0.01" value="1" aria-label="Zoom"><span>+</span></label><div class="vinci-cropper-actions"><button type="button" class="center">Centralizar</button><div><button type="button" class="cancel">Cancelar</button><button type="button" class="apply">Aplicar</button></div></div></div></section>`;document.body.appendChild(overlay);document.body.style.overflow="hidden";
const stage=overlay.querySelector(".vinci-cropper-stage"),canvas=overlay.querySelector("canvas"),ctx=canvas.getContext("2d"),zoomInput=overlay.querySelector('input[type="range"]');let baseScale=1,zoom=1,offsetX=0,offsetY=0,dragging=false,lastX=0,lastY=0,closed=false;
function currentScale(){return baseScale*zoom}function clamp(){const scale=currentScale(),drawW=image.naturalWidth*scale,drawH=image.naturalHeight*scale,maxX=Math.max(0,(drawW-canvas.width)/2),maxY=Math.max(0,(drawH-canvas.height)/2);offsetX=Math.max(-maxX,Math.min(maxX,offsetX));offsetY=Math.max(-maxY,Math.min(maxY,offsetY))}
function draw(){if(!canvas.width||!canvas.height)return;const scale=currentScale(),drawW=image.naturalWidth*scale,drawH=image.naturalHeight*scale,x=(canvas.width-drawW)/2+offsetX,y=(canvas.height-drawH)/2+offsetY;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(image,x,y,drawW,drawH)}
function sizeCanvas(){const rect=stage.getBoundingClientRect(),dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.max(1,Math.round(rect.width*dpr));canvas.height=Math.max(1,Math.round(rect.height*dpr));canvas.style.width=`${rect.width}px`;canvas.style.height=`${rect.height}px`;baseScale=Math.max(canvas.width/image.naturalWidth,canvas.height/image.naturalHeight);clamp();draw()}
function reset(){zoom=1;offsetX=0;offsetY=0;zoomInput.value="1";clamp();draw()}function finish(value){if(closed)return;closed=true;document.body.style.overflow="";overlay.remove();window.removeEventListener("resize",sizeCanvas);resolve(value)}
zoomInput.addEventListener("input",()=>{zoom=Number(zoomInput.value)||1;clamp();draw()});stage.addEventListener("wheel",e=>{e.preventDefault();zoom=Math.max(1,Math.min(3,zoom+(e.deltaY<0?.08:-.08)));zoomInput.value=String(zoom);clamp();draw()},{passive:false});stage.addEventListener("pointerdown",e=>{dragging=true;lastX=e.clientX;lastY=e.clientY;stage.classList.add("dragging");stage.setPointerCapture?.(e.pointerId)});stage.addEventListener("pointermove",e=>{if(!dragging)return;const rect=stage.getBoundingClientRect();offsetX+=(e.clientX-lastX)*(canvas.width/rect.width);offsetY+=(e.clientY-lastY)*(canvas.height/rect.height);lastX=e.clientX;lastY=e.clientY;clamp();draw()});const end=()=>{dragging=false;stage.classList.remove("dragging")};stage.addEventListener("pointerup",end);stage.addEventListener("pointercancel",end);overlay.querySelector(".center").onclick=reset;overlay.querySelector(".cancel").onclick=()=>finish(null);overlay.querySelector(".vinci-cropper-close").onclick=()=>finish(null);overlay.onclick=e=>{if(e.target===overlay)finish(null)};
overlay.querySelector(".apply").onclick=async function(){this.disabled=true;this.textContent="Preparando...";try{const out=document.createElement("canvas");out.width=outputWidth;out.height=outputHeight;const octx=out.getContext("2d"),rx=outputWidth/canvas.width,ry=outputHeight/canvas.height,scale=currentScale(),drawW=image.naturalWidth*scale,drawH=image.naturalHeight*scale,x=(canvas.width-drawW)/2+offsetX,y=(canvas.height-drawH)/2+offsetY;octx.drawImage(image,x*rx,y*ry,drawW*rx,drawH*ry);const blob=await canvasBlob(out,"image/webp",.9);finish(new File([blob],kind==="banner"?"banner.webp":"avatar.webp",{type:"image/webp",lastModified:Date.now()}))}catch(err){this.disabled=false;this.textContent="Aplicar";reject(err)}};window.addEventListener("resize",sizeCanvas);requestAnimationFrame(sizeCanvas)})}
window.VinciImageCropper={open};})();