(function(){
"use strict";
const $=s=>document.querySelector(s), roomId=new URLSearchParams(location.search).get("id");
if(!roomId)return;
let user=null,game=null,members=[],profiles=new Map(),submissions=[],votes=[],myStats={xp:0,games_played:0,wins:0,equipped_frame:null},unlocks=new Set(),unlockDates=new Map(),usageMap=new Map(),shopFilter='featured',timer=null,selectedVote=null;
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const media=url=>window.VinciMedia?.resolveUrl?window.VinciMedia.resolveUrl(url):Promise.resolve(url);
const COSMETICS=[
 {key:'aurora',name:'Aurora',req:'Jogue 1 partida',desc:'Luzes suaves em movimento.',category:'classic',rarity:'Comum',release:1},
 {key:'orbit',name:'Neon Orbit',req:'Jogue 3 partidas',desc:'Órbita azul e violeta.',category:'classic',rarity:'Comum',release:2},
 {key:'solar',name:'Solar Flare',req:'Jogue 5 partidas',desc:'Chamas douradas da Vinci.',category:'classic',rarity:'Incomum',release:3},
 {key:'champion',name:'Champion Halo',req:'Vença 1 partida',desc:'Halo reservado a vencedores.',category:'classic',rarity:'Incomum',release:4},
 {key:'prism',name:'Prism',req:'Jogue 10 partidas',desc:'Espectro vivo multicolorido.',category:'classic',rarity:'Rara',release:5},
 {key:'constellation',name:'Constellation',req:'Jogue 25 partidas',desc:'Céu estrelado ao redor do avatar.',category:'rare',rarity:'Rara',release:6},
 {key:'legend',name:'Vinci Legend',req:'Vença 10 partidas',desc:'Arco lendário multicolorido.',category:'rare',rarity:'Épica',release:7},
 {key:'celestial_wings',name:'Celestial Wings',req:'40 partidas + 5 vitórias',desc:'Asas de luz celestial que respiram ao redor do avatar.',category:'rare',rarity:'Épica',release:8},
 {key:'sakura_spirit',name:'Sakura Spirit',req:'60 partidas + 8 vitórias',desc:'Pétalas vivas flutuando em volta do perfil.',category:'rare',rarity:'Épica',release:9},
 {key:'inferno_dragon',name:'Inferno Dragon',req:'80 partidas + 15 vitórias',desc:'Asas de dragão, brasas vivas, crista dracônica e um núcleo de fogo ancestral.',category:'rare',rarity:'Épica',release:10},
 {key:'lunar_crown',name:'Lunar Crown',req:'100 partidas + 20 vitórias',desc:'Coroa lunar com luas e estrelas em órbita.',category:'mythic',rarity:'Mítica',release:11},
 {key:'seraph_prism',name:'Seraph Prism',req:'150 partidas + 30 vitórias',desc:'Asas prismáticas vivas, halo celestial, partículas orbitais e um núcleo de luz suspenso.',category:'mythic',rarity:'Mítica',release:12},
 {key:'eternal_vinci',name:'Eternal Vinci',req:'250 partidas + 50 vitórias',desc:'Coroa, órbitas e partículas Vinci.',category:'mythic',rarity:'Lendária',release:13},
 {key:'crystal_garden',name:'Crystal Garden',req:'70 partidas + 12 vitórias',desc:'Cristais florescem em volta do avatar com reflexos vivos.',category:'rare',rarity:'Épica',release:14},
 {key:'midnight_butterfly',name:'Midnight Butterfly',req:'120 partidas + 22 vitórias',desc:'Borboletas vivas percorrem a moldura sob estrelas e um amuleto de lua crescente.',category:'mythic',rarity:'Mítica',release:15},
 {key:'ocean_guardian',name:'Ocean Guardian',req:'180 partidas + 35 vitórias',desc:'Peixes nadando ao redor do avatar, bolhas e um amuleto marítimo encantado.',category:'mythic',rarity:'Mítica',release:16},
 {key:'cyber_koi',name:'Cyber Koi',req:'220 partidas + 45 vitórias',desc:'Koi cibernéticos nadam por circuitos neon ao redor de um núcleo digital.',category:'mythic',rarity:'Lendária',release:17},
 {key:'royal_phoenix',name:'Royal Phoenix',req:'300 partidas + 70 vitórias',desc:'Asas de fênix, coroa e brasas douradas.',category:'mythic',rarity:'Lendária',release:18},
 {key:'galaxy_crown',name:'Galaxy Crown',req:'400 partidas + 100 vitórias',desc:'Uma pequena galáxia inteira coroando seu perfil.',category:'mythic',rarity:'Relíquia',release:19},
 {key:'yakodev_core',name:'DEV//CORE',req:'EXCLUSIVA • @yakodevofc',desc:'Terminal vivo, código em órbita e halo verde de desenvolvedor.',category:'exclusive',rarity:'Fundador',release:100,exclusiveTo:'yakodevofc'}
];
function gameName(t){return t==='flash'?'Vinci Flash':t==='who_took'?'Quem Tirou?':'Blind Caption'}
async function loadProfiles(ids){const list=[...new Set(ids.filter(Boolean))];if(!list.length)return;const{data}=await db.from('profiles').select('id,username,name,avatar_url').in('id',list);for(const p of data||[])profiles.set(p.id,p)}
async function loadMembers(){const{data}=await db.from('vinci_room_members').select('user_id,role').eq('room_id',roomId);members=data||[];await loadProfiles(members.map(x=>x.user_id))}
function xpLevel(xp){const level=Math.floor((xp||0)/200)+1,start=(level-1)*200,within=(xp||0)-start;return{level,within,need:200,pct:Math.min(100,within/2)}}
async function loadProgress(){
 const [{data:s},{data:u},{data:all}]=await Promise.all([
  db.from('vinci_game_profiles').select('*').eq('user_id',user.id).maybeSingle(),
  db.from('vinci_game_unlocks').select('cosmetic_key,unlocked_at').eq('user_id',user.id),
  db.from('vinci_game_profiles').select('equipped_frame')
 ]);
 myStats=s||{xp:0,games_played:0,wins:0,equipped_frame:null};
 unlocks=new Set((u||[]).map(x=>x.cosmetic_key));unlockDates=new Map((u||[]).map(x=>[x.cosmetic_key,x.unlocked_at]));usageMap=new Map();
 for(const row of all||[]){if(row.equipped_frame)usageMap.set(row.equipped_frame,(usageMap.get(row.equipped_frame)||0)+1)}
 renderProgress();renderCosmetics();window.dispatchEvent(new CustomEvent('vinci-cosmetics-changed'))
}
function renderProgress(){const p=profiles.get(user.id)||{},lv=xpLevel(myStats.xp||0),box=$('#gamesProgress');if(!box)return;box.innerHTML=`<div class="game-profile-line" data-user-id="${user.id}"><img src="${esc(p.avatar_url||'assets/default-avatar.png.png')}" onerror="this.src='assets/default-avatar.png.png'"><div class="game-profile-main"><strong>@${esc(p.username||'você')}</strong><small>${myStats.xp||0} XP total</small></div><span class="game-level">NÍVEL ${lv.level}</span></div><div class="xp-track"><span style="width:${lv.pct}%"></span></div><div class="game-stats"><div class="game-stat"><strong>${myStats.games_played||0}</strong><small>PARTIDAS</small></div><div class="game-stat"><strong>${myStats.wins||0}</strong><small>VITÓRIAS</small></div><div class="game-stat"><strong>${unlocks.size}</strong><small>COSMÉTICOS</small></div></div>`}
function previewFrame(key){const art=['celestial_wings','sakura_spirit','inferno_dragon','lunar_crown','seraph_prism','eternal_vinci','crystal_garden','midnight_butterfly','ocean_guardian','cyber_koi','royal_phoenix','galaxy_crown','yakodev_core'].includes(key)?'<i class="vinci-frame-art" aria-hidden="true"><b></b><b></b><b></b><b></b></i>':'';return `<span class="vinci-frame-wrap vinci-frame-${key}">${art}<img src="${esc((profiles.get(user.id)||{}).avatar_url||'assets/default-avatar.png.png')}" onerror="this.src='assets/default-avatar.png.png'"></span>`}
function shopItems(){const username=String((profiles.get(user.id)||{}).username||'').toLowerCase();let list=COSMETICS.filter(c=>!c.exclusiveTo||c.exclusiveTo===username);if(shopFilter==='recent')list=[...list].sort((a,b)=>b.release-a.release);else if(shopFilter==='popular')list=[...list].sort((a,b)=>(usageMap.get(b.key)||0)-(usageMap.get(a.key)||0));else if(['classic','rare','mythic','exclusive'].includes(shopFilter))list=list.filter(c=>c.category===shopFilter);else list=[...list].sort((a,b)=>{const ae=unlocks.has(a.key)?1:0,be=unlocks.has(b.key)?1:0;return be-ae||b.release-a.release});return list}
function renderCosmetics(){const grid=$('#cosmeticsGrid');if(!grid)return;const list=shopItems();document.querySelectorAll('[data-shop-filter]').forEach(b=>b.classList.toggle('active',b.dataset.shopFilter===shopFilter));const title=$('#cosmeticsSectionTitle');if(title)title.textContent=({featured:'Destaques',recent:'Novidades',popular:'Mais usadas',classic:'Clássicas',rare:'Raras',mythic:'Míticas',exclusive:'Exclusivas'})[shopFilter]||'Coleção';grid.innerHTML=list.map(c=>{const open=unlocks.has(c.key),eq=myStats.equipped_frame===c.key,pop=usageMap.get(c.key)||0,date=unlockDates.get(c.key);return `<article class="cosmetic-card ${open?'':'locked'} ${eq?'equipped':''}"><div class="cosmetic-rarity">${esc(c.rarity)}</div><div class="cosmetic-preview">${previewFrame(c.key)}</div><h4>${esc(c.name)}</h4><p>${esc(c.desc)}</p><div class="cosmetic-meta"><span>${esc(c.req)}</span>${shopFilter==='popular'?`<b>${pop} usando</b>`:''}${date?`<b>✓ conquistada</b>`:''}</div><button type="button" data-equip-frame="${c.key}" ${open?'':'disabled'}>${open?(eq?'✓ Equipada':'Equipar'):'🔒 Bloqueada'}</button></article>`}).join('')+`<article class="cosmetic-card ${myStats.equipped_frame?'':'equipped'}"><div class="cosmetic-rarity">CLÁSSICO</div><div class="cosmetic-preview"><img src="${esc((profiles.get(user.id)||{}).avatar_url||'assets/default-avatar.png.png')}" style="width:55px;height:55px;border-radius:50%;object-fit:cover"></div><h4>Sem moldura</h4><p>Visual original do Vinci.</p><button type="button" data-equip-frame="">${myStats.equipped_frame?'Usar':'✓ Equipada'}</button></article>`;grid.querySelectorAll('[data-equip-frame]').forEach(b=>b.onclick=()=>equipFrame(b.dataset.equipFrame))}
async function equipFrame(key){const{error}=await db.rpc('vinci_equip_game_frame',{p_frame:key});if(error){alert(error.message);return}myStats.equipped_frame=key||null;renderCosmetics();renderProgress();window.dispatchEvent(new CustomEvent('vinci-cosmetics-changed'))}
async function loadLatestGame(){const{data,error}=await db.from('vinci_room_games').select('*').eq('room_id',roomId).order('created_at',{ascending:false}).limit(1).maybeSingle();if(error&&error.code!=='PGRST116'){showInstall(error);return}game=data||null;if(game){await loadGameData();await maybeFinalize()}renderGame();renderCooldown()}
function showInstall(error){$('#activeGameArea').innerHTML=`<div class="game-toast bad">${esc(String(error?.message||'').includes('vinci_room_games')?'Instale VINCI_1_0_ROOMS_PATCH_06_GAMES.sql no Supabase.':error?.message||'Erro ao carregar jogos.')}</div>`}
async function loadGameData(){if(!game)return;const [{data:s},{data:v}]=await Promise.all([db.from('vinci_room_game_submissions').select('*').eq('game_id',game.id).order('created_at'),db.from('vinci_room_game_votes').select('*').eq('game_id',game.id)]);submissions=s||[];votes=v||[];await loadProfiles([...submissions.map(x=>x.user_id),game.winner_user_id].filter(Boolean))}
function allSubmitted(){return members.length>0&&submissions.length>=members.length}
function submissionPhase(){return game&&game.status==='active'&&Date.now()<new Date(game.submit_ends_at).getTime()&&!allSubmitted()}
function votingPhase(){return game&&game.status==='active'&&game.game_type!=='who_took'&&!submissionPhase()&&Date.now()<new Date(game.ends_at).getTime()}
function timeLeft(){if(!game)return 0;const target=submissionPhase()?game.submit_ends_at:game.ends_at;return Math.max(0,new Date(target).getTime()-Date.now())}
function fmt(ms){const s=Math.ceil(ms/1000),m=Math.floor(s/60),r=s%60;return `${String(m).padStart(2,'0')}:${String(r).padStart(2,'0')}`}
function renderCooldown(){const box=$('#gamesCooldown'),buttons=document.querySelectorAll('[data-start-game]');if(!game){box.classList.add('hidden');buttons.forEach(b=>b.disabled=false);return}const until=new Date(game.created_at).getTime()+10*60*1000,left=until-Date.now(),active=game.status==='active'&&Date.now()<new Date(game.ends_at).getTime();buttons.forEach(b=>b.disabled=left>0||active);if(left>0){box.classList.remove('hidden');box.textContent=`⏳ Próxima partida disponível em ${fmt(left)}. O limite é 1 partida a cada 10 minutos por Room.`}else{box.classList.add('hidden')}}
async function renderGame(){clearInterval(timer);const area=$('#activeGameArea');if(!game){area.innerHTML='<div class="game-toast">Escolha um jogo para começar. A Room inteira participa da mesma partida.</div>';return}let body='';const mine=submissions.find(x=>x.user_id===user.id),winner=game.winner_user_id?profiles.get(game.winner_user_id):null;
if(game.game_type==='flash')body=await flashBody(mine);else if(game.game_type==='who_took')body=await whoBody(mine);else body=await captionBody(mine);
const phase=game.status==='finished'?'FINALIZADO':submissionPhase()?'PARTICIPE AGORA':game.game_type==='who_took'?'RESULTADO':'VOTAÇÃO';area.innerHTML=`<article class="active-game-card"><header class="active-game-head"><div><span>${phase}</span><h3>${esc(gameName(game.game_type))}</h3></div><strong id="gameTimer" class="game-timer">${game.status==='finished'?'FIM':fmt(timeLeft())}</strong></header><div class="active-game-body">${body}${game.status==='finished'?`<div class="game-result-banner"><span>🏆 VENCEDOR</span><strong>${winner?'@'+esc(winner.username||'usuário'):'Sem vencedor'}</strong><p>${winner?'Recebeu +60 XP e progresso para novas molduras.':'A partida terminou sem uma resposta vencedora.'}</p></div>`:''}</div></article>`;bindGameActions();if(game.status==='active')timer=setInterval(tick,1000)}
async function flashBody(mine){if(submissionPhase()){return `<h3 class="game-prompt">${esc(game.prompt)}</h3><p class="game-helper">Você tem 90 segundos. Tire a foto agora e envie antes do relógio zerar.</p>${mine?'<div class="game-toast good">✓ Sua foto foi enviada. Esperando os outros...</div>':'<div class="game-actions"><button id="sendFlashPhoto" class="game-action-primary" type="button">📷 Tirar / escolher foto</button></div>'}`}
if(!submissions.length)return '<div class="game-toast">Ninguém enviou foto nesta rodada.</div>';let cards='';for(const s of submissions){const u=await media(s.image_url);cards+=`<button class="game-submission" data-game-vote="${s.id}" ${s.user_id===user.id?'disabled':''}><img src="${esc(u||'')}" alt="Foto do Vinci Flash"></button>`}const myVote=votes.find(v=>v.voter_id===user.id);return `<h3 class="game-prompt">Qual foto venceu o Flash?</h3><p class="game-helper">Você não pode votar na própria foto.</p><div class="game-submissions">${cards}</div>${myVote?'<div class="game-toast good">✓ Voto registrado.</div>':'<button id="confirmGameVote" class="game-action-primary" type="button" disabled style="margin-top:10px">Confirmar voto</button>'}`}
async function whoBody(mine){const img=await media(game.image_url);let options=members.map(m=>{const p=profiles.get(m.user_id)||{};return `<button class="game-player" data-guess-user="${m.user_id}" type="button"><img src="${esc(p.avatar_url||'assets/default-avatar.png.png')}" onerror="this.src='assets/default-avatar.png.png'"><strong>@${esc(p.username||'usuario')}</strong></button>`}).join('');return `<div class="game-image-stage mystery"><img src="${esc(img||'')}" alt="Foto misteriosa"></div><h3 class="game-prompt">Quem tirou essa foto?</h3><p class="game-helper">Escolha alguém da Room. O autor só é revelado no resultado.</p>${mine?`<div class="game-toast ${mine.is_correct?'good':'bad'}">${mine.is_correct?'✓ Você acertou!':'✕ Seu palpite foi registrado.'}</div>`:`<div class="game-player-grid">${options}</div><button id="confirmGuess" class="game-action-primary" type="button" disabled style="margin-top:10px">Confirmar palpite</button>`}`}
async function captionBody(mine){const img=await media(game.image_url);if(submissionPhase())return `<div class="game-image-stage"><img src="${esc(img||'')}" alt="Foto para legenda"></div><h3 class="game-prompt">${esc(game.prompt)}</h3><p class="game-helper">O nome de quem escreveu fica escondido durante a votação.</p>${mine?'<div class="game-toast good">✓ Legenda enviada. Agora espera o caos.</div>':'<input id="captionGameInput" class="game-input" maxlength="180" placeholder="Escreva sua legenda..."><button id="sendCaptionGame" class="game-action-primary" type="button">Enviar legenda</button>'}`;if(!submissions.length)return '<div class="game-toast">Ninguém escreveu uma legenda nesta rodada.</div>';const myVote=votes.find(v=>v.voter_id===user.id);const cards=submissions.map(s=>`<button class="game-submission" data-game-vote="${s.id}" ${s.user_id===user.id?'disabled':''}><div class="caption-choice">${esc(s.content||'')}</div></button>`).join('');return `<div class="game-image-stage"><img src="${esc(img||'')}" alt="Foto do Blind Caption"></div><h3 class="game-prompt">Qual é a melhor legenda?</h3><div class="game-submissions">${cards}</div>${myVote?'<div class="game-toast good">✓ Voto registrado.</div>':'<button id="confirmGameVote" class="game-action-primary" type="button" disabled style="margin-top:10px">Confirmar voto</button>'}`}
function bindGameActions(){const fp=$('#sendFlashPhoto');if(fp)fp.onclick=()=>$('#flashPhotoInput').click();const cp=$('#sendCaptionGame');if(cp)cp.onclick=()=>submitCaption();let guess=null;document.querySelectorAll('[data-guess-user]').forEach(b=>b.onclick=()=>{guess=b.dataset.guessUser;document.querySelectorAll('[data-guess-user]').forEach(x=>x.classList.toggle('selected',x===b));$('#confirmGuess').disabled=false});if($('#confirmGuess'))$('#confirmGuess').onclick=()=>guess&&submitGame({p_guess_user_id:guess});selectedVote=null;document.querySelectorAll('[data-game-vote]').forEach(b=>b.onclick=()=>{if(b.disabled)return;selectedVote=b.dataset.gameVote;document.querySelectorAll('[data-game-vote]').forEach(x=>x.classList.toggle('selected',x===b));if($('#confirmGameVote'))$('#confirmGameVote').disabled=false});if($('#confirmGameVote'))$('#confirmGameVote').onclick=()=>voteGame()}
async function startGame(type){document.querySelectorAll('[data-start-game]').forEach(b=>b.disabled=true);const{data,error}=await db.rpc('vinci_start_room_game',{p_room_id:roomId,p_game_type:type});if(error){alert(error.message.includes('vinci_start_room_game')?'Rode VINCI_1_0_ROOMS_PATCH_06_GAMES.sql no Supabase.':error.message);renderCooldown();return}game=Array.isArray(data)?data[0]:data;submissions=[];votes=[];renderCooldown();await renderGame()}
async function uploadFlash(file){if(!file||!game)return;const ext=(file.name.split('.').pop()||'jpg').replace(/[^a-z0-9]/gi,'').toLowerCase()||'jpg',path=`${user.id}/rooms/${roomId}/games/${game.id}/${crypto.randomUUID()}.${ext}`;const{error}=await db.storage.from('vinci-images').upload(path,file,{contentType:file.type||'image/jpeg'});if(error){alert(error.message);return}const{data}=db.storage.from('vinci-images').getPublicUrl(path);const ok=await submitGame({p_image_url:data.publicUrl,p_storage_path:path});if(!ok)await db.storage.from('vinci-images').remove([path])}
async function submitCaption(){const val=$('#captionGameInput')?.value.trim();if(!val)return;await submitGame({p_content:val})}
async function submitGame(extra){const payload={p_game_id:game.id,p_content:null,p_image_url:null,p_storage_path:null,p_guess_user_id:null,...extra};const{data,error}=await db.rpc('vinci_submit_room_game',payload);if(error){alert(error.message);return false}await Promise.all([loadGameData(),loadProgress()]);await maybeFinalize();await renderGame();return true}
async function voteGame(){if(!selectedVote)return;const{error}=await db.rpc('vinci_vote_room_game',{p_game_id:game.id,p_submission_id:selectedVote});if(error){alert(error.message);return}await loadGameData();await maybeFinalize();await renderGame()}
async function maybeFinalize(){if(!game||game.status==='finished')return;const{data,error}=await db.rpc('vinci_finalize_room_game',{p_game_id:game.id});if(!error&&data){const g=Array.isArray(data)?data[0]:data;if(g?.status==='finished'){game=g;await Promise.all([loadGameData(),loadProgress()])}}}
async function tick(){if(!game)return;const el=$('#gameTimer');if(el)el.textContent=fmt(timeLeft());renderCooldown();if(timeLeft()<=0){clearInterval(timer);await loadGameData();await maybeFinalize();await renderGame()}}
async function refreshGame(){if(!game)return;const{data}=await db.from('vinci_room_games').select('*').eq('id',game.id).maybeSingle();if(data)game=data;await loadGameData();await maybeFinalize();await renderGame()}
function bindGamesUI(){document.querySelectorAll('[data-shop-filter]').forEach(b=>b.onclick=()=>{shopFilter=b.dataset.shopFilter;renderCosmetics()});const open=$('#openCosmeticsButton'),panel=$('#cosmeticsPanel'),close=$('#closeCosmeticsButton');if(open&&panel)open.onclick=()=>{panel.classList.remove('hidden');document.body.classList.add('cosmetics-open')};if(close&&panel)close.onclick=()=>{panel.classList.add('hidden');document.body.classList.remove('cosmetics-open')};if(panel)panel.addEventListener('click',e=>{if(e.target===panel){panel.classList.add('hidden');document.body.classList.remove('cosmetics-open')}});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&panel&&!panel.classList.contains('hidden')){panel.classList.add('hidden');document.body.classList.remove('cosmetics-open')}})}
async function init(){bindGamesUI();const{data}=await db.auth.getUser();user=data?.user;if(!user)return;await loadMembers();await loadProfiles([user.id]);if(!members.some(m=>m.user_id===user.id))return;await loadProgress();await loadLatestGame();document.querySelectorAll('[data-start-game]').forEach(b=>b.onclick=()=>startGame(b.dataset.startGame));const photo=$('#flashPhotoInput');if(photo)photo.onchange=e=>{const f=e.target.files?.[0];e.target.value='';if(f)uploadFlash(f)};db.channel(`room-games-${roomId}`).on('postgres_changes',{event:'*',schema:'public',table:'vinci_room_games',filter:`room_id=eq.${roomId}`},refreshGame).on('postgres_changes',{event:'*',schema:'public',table:'vinci_room_game_submissions',filter:`room_id=eq.${roomId}`},refreshGame).on('postgres_changes',{event:'*',schema:'public',table:'vinci_room_game_votes',filter:`room_id=eq.${roomId}`},refreshGame).subscribe()}
init();
})();
