(function(){"use strict";
function init(){const original=document.querySelector('.room-tabs'),heroActions=document.querySelector('.room-hero-actions');if(!original||original.dataset.focusReady==='1')return;original.dataset.focusReady='1';original.classList.add('focus-original-room-tabs');
const nav=document.createElement('nav');nav.className='focus-room-tabs';nav.innerHTML='<button type="button" class="active" data-focus-room="today">Hoje</button><button type="button" data-focus-room="chat">Chat</button><button type="button" data-focus-room="memories">Memórias</button><button type="button" data-focus-room="more">Mais</button>';original.insertAdjacentElement('beforebegin',nav);
const memories=document.createElement('section');memories.id='focus-room-memories';memories.className='focus-room-panel hidden';memories.innerHTML='<header><span>MEMÓRIAS</span><h2>O que vocês viveram</h2><p>Mural, arquivo e cápsulas ficam juntos agora.</p></header><div class="focus-room-cards"><button data-open-tab="mural"><i>▦</i><span><strong>Mural de hoje</strong><small>Fotos e votação do desafio atual.</small></span><b>›</b></button><button data-open-tab="murals"><i>◫</i><span><strong>Murais anteriores</strong><small>Reveja os desafios que já passaram.</small></span><b>›</b></button><button data-open-tab="capsules"><i>⌛</i><span><strong>Cápsulas do Tempo</strong><small>Memórias guardadas para o futuro.</small></span><b>›</b></button></div>';
const more=document.createElement('section');more.id='focus-room-more';more.className='focus-room-panel hidden';more.innerHTML='<header><span>MAIS DA ROOM</span><h2>Recursos secundários</h2><p>Continuam aqui, só não disputam atenção com o desafio e o chat.</p></header><div class="focus-room-cards"><button data-open-tab="games"><i>✦</i><span><strong>Jogos</strong><small>Vinci Flash, Quem Tirou? e Blind Caption.</small></span><b>›</b></button><button data-open-tab="ranking"><i>🏆</i><span><strong>Ranking</strong><small>Hall of Fame e vencedores da Room.</small></span><b>›</b></button><button data-focus-level><i>↗</i><span><strong>Nível da Room</strong><small>XP, progresso e temporada.</small></span><b>›</b></button><button data-focus-room-settings><i>⚙</i><span><strong>Configurações</strong><small>Nome, descrição, capa e gerenciamento.</small></span><b>›</b></button></div>';
original.insertAdjacentElement('afterend',more);original.insertAdjacentElement('afterend',memories);
function oldButton(tab){return original.querySelector(`[data-tab="${tab}"]`)}function hidePanels(){memories.classList.add('hidden');more.classList.add('hidden')}function activeFocus(key){nav.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.focusRoom===key))}function openOld(tab,category){hidePanels();oldButton(tab)?.click();activeFocus(category||tab)}
nav.querySelector('[data-focus-room="today"]').onclick=()=>openOld('today','today');nav.querySelector('[data-focus-room="chat"]').onclick=()=>openOld('chat','chat');nav.querySelector('[data-focus-room="memories"]').onclick=()=>{document.querySelectorAll('.room-tab').forEach(s=>s.classList.remove('active'));more.classList.add('hidden');memories.classList.remove('hidden');activeFocus('memories')};nav.querySelector('[data-focus-room="more"]').onclick=()=>{document.querySelectorAll('.room-tab').forEach(s=>s.classList.remove('active'));memories.classList.add('hidden');more.classList.remove('hidden');activeFocus('more')};
memories.querySelectorAll('[data-open-tab]').forEach(b=>b.onclick=()=>openOld(b.dataset.openTab,'memories'));more.querySelectorAll('[data-open-tab]').forEach(b=>b.onclick=()=>openOld(b.dataset.openTab,'more'));more.querySelector('[data-focus-level]').onclick=()=>{openOld('today','more');setTimeout(()=>document.getElementById('roomProgressPanel')?.scrollIntoView({behavior:'smooth',block:'center'}),80)};more.querySelector('[data-focus-room-settings]').onclick=()=>{const edit=document.getElementById('editRoomButton'),invite=document.getElementById('inviteMemberButton');if(edit&&!edit.classList.contains('hidden'))edit.click();else if(invite&&!invite.classList.contains('hidden'))invite.click();else alert('Você não tem opções de gerenciamento nesta Room.')};
original.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{const t=b.dataset.tab;if(t==='today')activeFocus('today');else if(t==='chat')activeFocus('chat');else if(['mural','murals','capsules'].includes(t))activeFocus('memories');else activeFocus('more')},true));
if(heroActions){const menu=document.createElement('div');menu.className='focus-room-actions-menu hidden';const trigger=document.createElement('button');trigger.type='button';trigger.className='room-soft-btn focus-room-actions-trigger';trigger.textContent='•••';trigger.setAttribute('aria-label','Mais opções da Room');const oldButtons=[...heroActions.querySelectorAll('#editRoomButton,#inviteMemberButton,#leaveRoomButton')];heroActions.append(trigger,menu);oldButtons.forEach(b=>menu.appendChild(b));trigger.onclick=e=>{e.stopPropagation();menu.classList.toggle('hidden')};menu.addEventListener('click',()=>setTimeout(()=>menu.classList.add('hidden'),30));document.addEventListener('click',e=>{if(!heroActions.contains(e.target))menu.classList.add('hidden')})}
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init()})();